/**
 * Apply Drizzle migrations to Neon non-interactively.
 *
 *   pnpm --filter @floe-dashboard/data db:migrate
 *
 * Reads SQL files from `drizzle/` (generated by `drizzle-kit generate`)
 * and runs each statement via the Neon HTTP driver. Idempotent: skips
 * statements that fail with "already exists" / "duplicate" errors.
 */

import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { neon } from "@neondatabase/serverless";

async function main() {
  const url = process.env.NEON_DATABASE_URL;
  if (!url) throw new Error("NEON_DATABASE_URL not set");
  const sql = neon(url);

  const drizzleDir = path.resolve(import.meta.dirname, "..", "drizzle");
  const files = (await readdir(drizzleDir))
    .filter((f) => f.endsWith(".sql"))
    .sort();
  if (files.length === 0) {
    console.error("No .sql files in drizzle/. Run `pnpm db:generate` first.");
    process.exit(1);
  }

  for (const file of files) {
    const fullPath = path.join(drizzleDir, file);
    const contents = await readFile(fullPath, "utf8");
    // Drizzle splits statements with `--> statement-breakpoint`.
    const statements = contents
      .split(/-->\s*statement-breakpoint/)
      .map((s) => s.trim())
      .filter(Boolean);
    console.log(`[migrate] ${file}: ${statements.length} statements`);
    for (let i = 0; i < statements.length; i++) {
      const stmt = statements[i]!;
      const summary = stmt.split("\n")[0]?.slice(0, 80) ?? "";
      try {
        await sql(stmt);
        console.log(`  [${i + 1}/${statements.length}] ✅ ${summary}`);
      } catch (err) {
        const msg = (err as Error).message;
        if (/already exists|duplicate/i.test(msg)) {
          console.log(`  [${i + 1}/${statements.length}] ⏭  (already applied) ${summary}`);
        } else {
          console.error(`  [${i + 1}/${statements.length}] ❌ ${summary}`);
          console.error(`     ${msg}`);
          throw err;
        }
      }
    }
  }
  console.log(`[migrate] done.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
